name: 'Auto merge bot'
description: 'Automatically merge pull request when all the checks have passed'
author: 'funSamy'
branding:
  color: orange
  icon: check-circle
inputs:
  github-token: # id of input
    description: 'Github token'
    required: true
  merge-method: # id of input
    description: 'Merge method'
    required: false
    default: 'squash'
  debug:
    description: 'Enable debug mode'
    required: false
    default: 'false'
outputs:
  sha:
    description: 'The SHA of the commit'
  merged:
    description: 'Whether the PR was merged or not'
  message:
    description: 'The message of the mermeg commit'
runs:
  using: 'node20'
  main: 'dist/index.js'
